### ISSUE TITLE
Revision Hash on multiple server/machine [URGENT]

### ISSUE THREAD

**Issue by kiddo13** [sindresorhus/gulp-rev#147] opened 2016-01-16 04:33 UTC
At first, it's fine when we only use one server.
But after we use multiple server, each machine generated different hash key.
The files are already sorted using `gulp-natural-sort`, and the hash generated consistently on each changes, but different on each machine.
Each machine is 64-bit and use the same OS (linux).

I'm not sure to ask on `rev-hash` repo or `gulp-rev`. 
But I asked here anyway, because it's more relevant to the cache issue.

**Comment by bobthecow** [comment] 2016-01-16 06:37
The hash generated only changes if the content changes. Are you concatenating files?

**Comment by kiddo13** [comment] 2016-01-16 09:01
Not just concat. I also use less, minify and uglify.

The previous problem was the hash keep changing even if the content was not.
But I already fixed it by using `gulp-natural-sort`.
Which means I would get the correct hash.
This worked perfectly, until we used multiple servers for our website.

Each server generated different hash after deploy.
They run the same command, and use the same code base.

Any idea what happened?

**Comment by bobthecow** [comment] 2016-01-16 09:06
Are they running slightly different versions of dependencies? Are you shrinkwrapping?

**Comment by kiddo13** [comment] 2016-01-16 09:27
I'm not so sure about the version.
But I used bower to manage the dependencies.
So I assume it should have the same version.
How could I make sure they use the same version?

BTW, I used `gulp-cached` and `gulp-remember`, do you think they are related?

**Comment by sindresorhus** [comment] 2016-01-16 21:24
Different Node.js versions might also cause different hashes.

Closing this as it's a support question, but feel free continue discussing.

**Closed by sindresorhus** 2016-01-16 21:24 UTC

**Comment by bobthecow** [comment] 2016-01-17 16:08
Yeah, I wouldn't be surprised if `gulp-cached` or `gulp-remember` did something. You can try disabling them and seeing if that sorts it out.

Are you running them in production?

**Comment by kiddo13** [comment] 2016-01-20 14:27
@bobthecow sorry for my late reply.

I have fixed the problem, thanks to your help.
`gulp-cached` or `gulp-remember` cause the inconsistent content.
I use `gulp-if` to run them only in development.

```
   // ...
   .pipe(gulpif(isProduction, cached()))
   // ...
   .pipe(gulpif(isProduction, remember()))
   // ...
```

**Comment by bobthecow** [comment] 2016-01-20 15:02
Great! Glad you were able to sort it out.

**Comment by ngaspar** [comment] 2016-12-12 12:29
A long time since the last posted solution - I'm having the same problem, but not caused by those modules (cached and remember). Node, npm and gulp have the same versions in the different servers. Additionally all dependencies have the same versions too. I recently added 2 new webapp servers and they always end up with different asset hashes. I couldn't find the pattern so far. Any ideas anyone?
