### ISSUE TITLE
Hash does not change

### ISSUE THREAD

**Issue by damionvega** [sindresorhus/gulp-rev#189] opened 2016-07-17 17:47 UTC
Or is this not a bug? I'm using gulp-rev for cache-busting.

````js
gulp.task('revision', function () {
  return gulp.src(['dist/**/*.css', 'dist/**/*.js'])
    .pipe($.rev())
    .pipe(gulp.dest('dist'))
    .pipe($.rev.manifest())
    .pipe(gulp.dest('dist'))
})

gulp.task('revreplace', ['revision'], function () {
  var manifest = gulp.src('./dist/rev-manifest.json')

  return gulp.src('dist/index.html')
    .pipe($.revReplace({ manifest: manifest }))
    .pipe(gulp.dest('dist'))
})
````
![screenshot 2016-07-17 11 42 03](https://cloud.githubusercontent.com/assets/7221494/16902168/f01f5daa-4c13-11e6-9f1c-f1fa92106d31.png)

**Comment by bobthecow** [comment] 2016-07-17 17:54
The hash is content-based. So for subsequent builds, if the file is exactly the same it will get the same hash.

**Comment by lukeed** [comment] 2016-07-17 18:10
👍 What @bobthecow said. There isn't any point in generating a new, unique file if its contents are exactly the same.

Closing since this is by design. Thanks!

**Comment by damionvega** [comment] 2016-07-17 18:11
OK that makes a lot more sense. Thank you.

**Closed by lukeed** 2016-07-17 18:10 UTC
