### ISSUE TITLE
Incorrectly change some files (eg: dataTables.fixedHeader.js)

### ISSUE THREAD

**Issue by evildancer** [sindresorhus/gulp-rev#211] opened 2017-04-21 07:42 UTC
### Description
use gulp-rev:

dataTables.fixedHeader.js  =>  dataTables-236fe04c3a.fixedHeader.min.js

For these files, it did a wrong operation

**Comment by Zhouzi** [comment] 2017-04-21 09:54
Are you suggesting that the result should be `dataTables.fixedHeader.min-236fe04c3a.js` instead of `dataTables-236fe04c3a.fixedHeader.min.js`?

As long as the manifest points to the right files, it shouldn't be an issue.

**Comment by evildancer** [comment] 2017-04-22 05:14
it should be `dataTables.fixedHeader.min-236fe04c3a.js`.
it is now `taTables-236fe04c3a.fixedHeader.min.js`, and the manifest points to the right files. but, 
When using gulp-rev-collector, it is not correct.

**Comment by lukeed** [comment] 2017-04-22 05:25
If the file paths are consistent across the filenames and the `rev-manifest.json`, then there is nothing wrong. It seems like your issue is with the `gulp-rev-collector` plugin -- not here.

FWIW, you _can_ change how file names are constructed. Please see [my previous answer](https://github.com/sindresorhus/gulp-rev/issues/186#issuecomment-229279896) on how to do so. You can setup the files however you want this way.

---

Marking as closed since this is intended behavior. However, please feel free to follow up with any questions. 😄

**Closed by lukeed** 2017-04-22 05:25 UTC
