### ISSUE TITLE
Replacing the hash function

### ISSUE THREAD

**Issue by ankon** [sindresorhus/gulp-rev#179] opened 2016-05-24 16:24 UTC
We've been using gulp-rev to process our asset files, but recently wanted to switch from content-based hashing to simply using the git revision number of project (the reasons aren't specifically interesting, I can share them if needed). I didn't really find a plugin that would easily replace gulp-rev, and still produce a suitable `rev-manifest.json` + be useable in combination with gulp-rev-replace. Instead I just hacked gulp-rev to replace the hashing function: https://github.com/Collaborne/gulp-git-rev/commit/d1094f4af4512784a14cbafc2a6fd50ca1568f1b

The diff looks a lot bigger than it is really ... but I was wondering: It would be nice if instead of forking the whole project it would be possible to use it as a library, and just create a small wrapper plugin that does the actual revision calculation.

Would it be interesting for this project to provide a patch into that direction?

**Comment by lukeed** [comment] 2016-05-24 17:04
Duplicate of #129.

If you _really_ wanted to, you can pass through a custom function that replaces the `file.revHash` with your package.json's version.

See bottom of #169 for a start on this approach.

**Closed by lukeed** 2016-05-24 17:04 UTC
